# Generated by Django 2.1.1 on 2018-10-17 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=42)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=42)),
                ('poster', models.CharField(max_length=200)),
                ('message_id', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=42)),
                ('delete', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, default='Hi~', max_length=420)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('picture', models.ImageField(blank=True, default='user-photos/hdfj3498whf23jdnfsjk382r.png', upload_to='user-photos')),
                ('header_photo', models.ImageField(blank=True, default='header-photos/hfjq74yr7HBKYG78hg7bFFY213.jpg', upload_to='header-photos')),
                ('jumbotron_title', models.CharField(blank=True, default='Welcome', max_length=40)),
                ('jumbotron_content', models.CharField(blank=True, default='Enjoy yourself!~', max_length=200)),
                ('friends', models.ManyToManyField(blank=True, to='grumblr.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserProfile'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserProfile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.Message'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grumblr.UserProfile'),
        ),
    ]
