# Generated by Django 2.1.1 on 2018-10-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delete',
        ),
    ]
