# Generated by Django 2.1.1 on 2018-11-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_remove_message_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
