# Generated by Django 2.1.1 on 2018-11-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20181112_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token_reg',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
